---
abstract: 'Base class for a family of (Mega)Traveller character generation modules'
author:
  - 'Peter L. Berghold <cpan@berghold.net>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPG-Traveller-Person
requires:
  Data::Dumper: 0
  Exporter: 0
  Getopt::Long: 0
  Moose: 0
  RPG::Dice: 1.1
  Test::More: 0.88
  Test::Pod::Coverage: 0
  constant: 0
  perl: 5.006
  strict: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Auth=COWDAWG
version: 1.020
